### ISSUE TITLE
Something went wrong: Optional(889 bytes)

### ISSUE THREAD

**Issue by scherzinqer123** [prine/ROGoogleTranslate#6]
I'm new to swift, I'm always getting that error which is Something went wrong: Optional(889 bytes). Would you please help me about that ? Thank you.

**Comment by prine** [comment]
Are you receiveing a '403' error code in the response?
If you get a 403 Response, please check your Google Api Account. Google recently changed the policies of the Translation Api and you have to add a credit card, otherwise you will receive a 403 Error.
